### ISSUE TITLE
Version without Docker?

### ISSUE THREAD

**Issue by mrbluecoat** [hyprspace/relay#1]
Any reason to include Docker in the stack? The Docker hypervisor and Ubuntu image seem like unnecessary weight for just relaying network traffic. Any chance you could document how to use relay directly?

**Comment by mrbluecoat** [comment]
Here's my current attempt:

```
sudo apt -t install -y git golang-go
mkdir -p /usr/local/bin/
cd /tmp
git clone https://github.com/hyprspace/relay
cd relay
go build -o hyprspace-relay .
sudo mv ./hyprspace-relay /usr/local/bin/
echo "$PATH" | grep -q "/usr/local/bin" || sudo ln -s /usr/local/bin/hyprspace-relay /usr/bin/hyprspace-relay
cd ~
```

However, running `hyprspace-relay` results in this error:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/hyprspace/relay/config.envParseClients(0x0, 0x0, 0x8a8606)
        /tmp/relay/config/env.go:50 +0x5a4
github.com/hyprspace/relay/config.init.0()
        /tmp/relay/config/config.go:41 +0x68
```

**Comment by mrbluecoat** [comment]
nm, needed the environment variables...

```
export RELAY_ID=[[INSERT YOUR PORTAL'S ID HERE]]
export RELAY_ADDRESS=[[INSERT YOUR RELAY'S INTERNAL IP ADDRESS HERE]]
export RELAY_PORT=8001
export RELAY_DISCOVERKEY=[[INSERT YOUR HYPRSPACE DISCOVERY KEY HERE]]
export RELAY_PRIVATEKEY=[[INSERT YOUR PORTAL'S PRIVATE KEY HERE]]
export RELAY_CLIENT_KEYS=[[INSERT YOUR CLIENT'S PUBLIC KEY HERE]]
export RELAY_CLIENT_PORTS=80,443
export RELAY_CLIENT_IPS=10.0.0.2
```

**Comment by mrbluecoat** [comment]
Where is the `peers env variable section` mentioned in Step 15?

**Comment by mrbluecoat** [comment]
nm, I found the issue: `RELAY_CLIENT_KEYS` in your README example should be `RELAY_CLIENT_IDS`

**Comment by mrbluecoat** [comment]
last post before I hand it over to the experts.. Running `hyprspace-relay` now gives me:

```Relay
Version: 0.0.1

[+] Creating LibP2P Node
[+] Setting Up Node Discovery via DHT
[+] Network Setup Complete...Waiting on Node Discovery
2021/09/11 03:10:39 error dialing remote addr connect tcp 10.1.1.2:443: operation timed out
```

**Comment by alecbcs** [comment]
> Any reason to include Docker in the stack? The Docker hypervisor and Ubuntu image seem like unnecessary weight for just relaying network traffic. Any chance you could document how to use relay directly?

Absolutely, I personally use `hyprspace-relay` as a docker container so that I can easily deploy it to cloud VMs without having to worry about dependencies. I would be open to also releasing it as a set of binaries however for those who don't use docker. 

> Where is the `peers env variable section` mentioned in Step 15?

Ah so good catch this should indeed be the **clients** env variable section not peers. Unfortunately I've been working on a couple of other projects and after setting this application up during a weekend I haven't gotten the chance to clean it up yet.

>  I found the issue: `RELAY_CLIENT_KEYS` in your README example should be `RELAY_CLIENT_IDS`

Good catch! I'd changed the language a couple of times internally and forgotten to update the README. (This is an important part of the tutorial however so thanks for seeing this. I'll fix it.)

**Comment by bmullan** [comment]
@alecbcs 

_I too would like to see a Non-Docker version of hyprspace-relay._

I use LXD Containers & VMs a lot so although I could run the Docker version of hyprspace-relay I'd rather not due to Docker/LXD redundancy of purpose.

thanks
brian
